# ==================== ORACLE DATABASE ====================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=EVENTSPHERE
spring.datasource.password=ton_mot_de_passe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==================== JWT ====================
jwt.secret=eventsphere2024SecretKeyPourJWTMinimum256BitsObligatoire!
jwt.expiration=86400000

# ==================== EMAIL SMTP (Gmail) ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eventsphere.app@gmail.com
spring.mail.password=xxxx_xxxx_xxxx_xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==================== GOOGLE OAUTH2 ====================
spring.security.oauth2.client.registration.google.client-id=TON_CLIENT_ID.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=TON_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/auth/oauth2/callback/google

# ==================== APP ====================
app.frontend-url=http://localhost:3000
app.otp.expiration-minutes=10
